language: python

python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "pypy"
  - "pypy3"

install:
  - pip install -r requirements.txt
  - pip install codecov

script:
  - coverage run python

after_script:
  - codecov
  - bash <(curl -s https://codecov.io/bash) && echo "Uploaded code coverage"
